{% set version = "2.10.4" %}
{% set bioconda_version = "2.10.4" %}
{% set ngs_version = "2.10.4" %}

package:
  name: sra-tools
  version: '{{ bioconda_version }}'

source:
  - url: https://github.com/ncbi/sra-tools/archive/{{version}}.tar.gz
    sha256: 7a65203421d81f4c4f61eff13bc965f4ef1a7231cedc02005e4ae3b886520441
    folder: sra-tools
  - url: https://github.com/ncbi/ncbi-vdb/archive/{{version}}.tar.gz
    sha256: b78d574b1b20c4b864a0358e0660481497fc1b269f9bee621b4aa7866d81dfb7
    folder: ncbi-vdb
  - url: https://github.com/ncbi/ngs/archive/{{ngs_version}}.tar.gz
    sha256: 6f5db2269c6afc8e51a50fbcab9c63f4b1d6b69e483c6acb40d8f9e52f8282b1
    folder: ngs

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ncbi-ngs-sdk
    - libxml2
    - hdf5
    - perl
  run:
    - perl
    - ncbi-ngs-sdk
    - libxml2
    - hdf5
    - perl-xml-libxml
    - perl-uri

test:
  commands:
    # "Frequently Used Tools"
    - sratools help
    # Ensure the old executable names still work
    - fastq-dump --help > /dev/null
    - prefetch --help > /dev/null
    - sam-dump --help > /dev/null
    - sra-pileup --help > /dev/null
    - vdb-config --help > /dev/null
    - vdb-decrypt --help > /dev/null
    - fastq-dump -N 1 -X 1 SRR000001 && grep '@SRR000001.1' SRR000001.fastq
    - fasterq-dump --help > /dev/null

about:
  home: https://github.com/ncbi/sra-tools
  license: Public Domain
  summary: SRA Toolkit and SDK from NCBI
  description:  |
    The SRA Toolkit and SDK from NCBI is a collection of tools and libraries
    for using data in the INSDC Sequence Read Archives.

extra:
  notes: 'After installation, you should run the configuration tool: ./vdb-config
    -i. This tool will setup your download/cache area for downloaded files and references.'
